### ISSUE TITLE
CRDs for Loki

### ISSUE THREAD

**Issue by a-mcf** [a-mcf/k3s-gitops#473]
Enable CRDS for the loki helm chart. This will allow self-monitoring to be re-enabled:
``` 
   test:
      # -- revisit later, requries self monitioring.
      enabled: false
    monitoring:
      selfMonitoring:
        # -- revisit this later, it requires crds
        enabled: false
```
